import { gql } from '@apollo/client';

// ── Fragments — DRY GraphQL operations ──────────────────────────────────────
// Instead of repeating field lists in every query/mutation,
// define reusable fragments. This is a key GraphQL best practice for scaling.
//
// Benefits:
// 1. DRY — change the fields in one place
// 2. Co-location — component knows exactly what data it needs
// 3. Type safety — fragment types can be generated by GraphQL codegen
//
// TODO 6e: Use these fragments in your queries/mutations
// HINT: In a query: ...SkillFields  (spread the fragment)

export const SKILL_FRAGMENT = gql`
  fragment SkillFields on Skill {
    id
    title
    category
    level
    maxLevel
    isMastered
    description
    tags
    xp
  }
`;

export const CATEGORY_STAT_FRAGMENT = gql`
  fragment CategoryStatFields on CategoryStat {
    category
    count
    avgLevel
    totalXP
    color
  }
`;

// TODO 6f: Update GET_SKILLS query in queries.js to use the fragment:
// import { SKILL_FRAGMENT } from './fragments';
// export const GET_SKILLS = gql`
//   ${SKILL_FRAGMENT}
//   query GetSkills($category: String) {
//     getSkills(category: $category) {
//       ...SkillFields
//     }
//   }
// `;
